server:
  port: 8503
spring:
  application:
    name: lychee-system
  datasource:
    url: jdbc:mysql://localhost:3306/lychee?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
feign:
  client:
    config:
      # 默认为所有的feign client做配置(注意和上例github-client是同级的)
      default:
        connectTimeout: 5000                        # 连接超时时间
        readTimeout: 5000                           # 读超时时间设置