server:
  port: 8501
spring:
  application:
    name: lychee-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: lychee-system
          uri: lb://lychee-system
          predicates:
            - Path=/system/**
        - id: lychee-auth
          uri: lb://lychee-auth
          predicates:
            - Path=/auth/**

skip:
  url:
    - /auth/oauth/login
